esphome:
  name: lifxtest
  platform: ESP8266
  board: d1_mini
  includes:
    - lifx-emulation.h
  platformio_options:
    lib_deps: ESPAsyncUDP

wifi:
  networks:
  - ssid: "YOURINFORMATIONHERE"
    password: !secret wifi
  fast_connect: TRUE
  
# Enable logging
logger:
  level: WARN
  esp8266_store_log_strings_in_flash: False
  
# Enable Home Assistant API
api:
  password: !secret ota
  reboot_timeout: 0s

ota:
  password: !secret ota

#this is for my bench test light, your pins may vary
output:
  - platform: esp8266_pwm
    pin: D1
    id: P1
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D2
    id: P2
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D5
    id: P5
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D6
    id: P6
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D7
    id: P7
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

light:
  - platform: rgb
    id: color_led
    name: "color_led"
    red: P7
    green: P6
    blue: P5
    
  - platform: cwww
    id: white_led
    name: "white_led"
    cold_white: P1
    warm_white: P2
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    
custom_component:
- lambda: |-
    const _locationUUID = "012d3356-bb39-4b1d-aa60-1466b992ca62";  
    uint64_t _locationUpdated = 1553350342028441856;
    
    auto lifxUdpSupport = new lifxUdp();
    lifxUdpSupport->beginUDP((byte *)WiFi.macAddress().c_str(), (char *)App.get_name().c_str());
    return {lifxUdpSupport};
