esphome:
  name: lifxtest
  platform: ESP8266
  board: d1_mini
  # Required for LIFX LAN support
  includes:
    - lifx-emulation.h
  platformio_options:
    lib_deps: ESPAsyncUDP

wifi:
  networks:
  - ssid: "YOURINFORMATIONHERE"
    password: !secret wifi
  fast_connect: TRUE
  
# Enable logging
logger:
  level: WARN
  esp8266_store_log_strings_in_flash: False
  
# Enable Home Assistant API
api:
  password: !secret ota
  reboot_timeout: 0s

ota:
  password: !secret ota

#this is for my bench test light, your pins may vary
output:
  - platform: esp8266_pwm
    pin: D1
    id: P1
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D2
    id: P2
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D5
    id: P5
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D6
    id: P6
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: D7
    id: P7
    #frequency: 4000 Hz
    #inverted: True
    min_power: 0
    max_power: 1

# Lifx emulation needs two discrete elements to control as coded below
light:
  - platform: rgb
    id: color_led
    name: "color_led"
    red: P7
    green: P6
    blue: P5
    
  - platform: cwww
    id: white_led
    name: "white_led"
    cold_white: P1
    warm_white: P2
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

# Lifx emulation needs UTC time to respond to packets correctly.  Code expects id: ha_time.
time:
  - platform: sntp
    id: ha_time

# Required component for Lifx support
custom_component:
- lambda: |-
  auto LifxLAN = new lifxUdp();

  LifxLAN->set_bulbLabel( App.get_name().c_str() );  
  WiFi.macAddress(LifxLAN->mac);

  LifxLAN->set_bulbLocation( "Test Location" );
  LifxLAN->set_bulbLocationGUID( "4b833820-49b1-4f97-b324-316098f259d3" );
  uint64_t locT = 1600358586632000000;  // epoch in msec * 1,000,000
  LifxLAN->set_bulbLocationTime( locT );

  LifxLAN->set_bulbGroup( "Test Group" );
  LifxLAN->set_bulbGroupGUID( "455820e8-3323-49f3-a7d0-598ba8092563" );
  uint64_t grpT = 1600358586632000000; // epoch in msec * 1,000,000
  LifxLAN->set_bulbGroupTime( grpT );

  LifxLAN->beginUDP();
  return {LifxLAN};
